In [1]:
import numpy as np

**Forming arrays**

In [2]:
my_array1d=([1,2,3,4,5,6])                             #Using lists

In [3]:
my_array2d=([1,2,3],[4,5,6],[7,8,9])

In [4]:
my_array1d

[1, 2, 3, 4, 5, 6]

In [5]:
my_array2d

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [6]:
my_array1d[1]

2

In [7]:
# my_array2d[0,0]   

In [8]:
# my_array2d[1,2]

In [9]:
my_array2d[0][0]   

1

In [10]:
my_array2d[1][2]

6

In [11]:
#### Printing 2d list as array
for i in my_array2d:
    for j in i:
        print (j,end=" ")
    print ()

1 2 3 
4 5 6 
7 8 9 


In [12]:
my_array1d=np.array([1,2,3,4,5,6,7])                       #Using numpy

In [13]:
my_array2d=np.array([[1,2,3],[4,5,6],[7,8,9],[5,4,6]])

In [14]:
my_array1d

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
my_array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 4, 6]])

In [16]:
my_array1d[3]

4

In [17]:
my_array2d[3,2]

6

In [18]:
my_array2d[2,1:]

array([8, 9])

In [19]:
my_array2d[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
my_array2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [21]:
my_array2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [22]:
my_array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 4, 6]])

In [23]:
my_array2d[:2,1:2]

array([[2],
       [5]])

In [24]:
my_array2da=np.array([[1,2,3,4,5],[4,5,6,5,4],[7,5,6,8,9],[5,7,4,3,6]])

In [25]:
my_array2da

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 5, 4],
       [7, 5, 6, 8, 9],
       [5, 7, 4, 3, 6]])

In [26]:
my_array2da[:,::1]

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 5, 4],
       [7, 5, 6, 8, 9],
       [5, 7, 4, 3, 6]])

In [27]:
my_array2da[:,::2]

array([[1, 3, 5],
       [4, 6, 4],
       [7, 6, 9],
       [5, 4, 6]])

In [28]:
my_array2da[::2,:]

array([[1, 2, 3, 4, 5],
       [7, 5, 6, 8, 9]])

In [29]:
my_array2da[::2,::2]

array([[1, 3, 5],
       [7, 6, 9]])

In [30]:
my_array1d.dtype


dtype('int32')

In [31]:
my_array2d.dtype


dtype('int32')

In [32]:
my_array1d.shape


(7,)

In [33]:
my_array1d.size


7

In [34]:
my_array2d.shape

(4, 3)

In [35]:
my_array2d.size

12

In [36]:
np.sum(my_array2d)

60

In [37]:
np.max(my_array2d)

9

In [38]:
np.min(my_array1d)

1

In [39]:
my_array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 4, 6]])

In [40]:
np.sort(my_array2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 6]])

In [41]:
ar1=np.array([1,2,3,4],dtype='int8')    

In [42]:
ar1


array([1, 2, 3, 4], dtype=int8)

In [43]:
ar1=np.array([1,2,3,4],np.int64)

In [44]:
ar1

array([1, 2, 3, 4], dtype=int64)

In [45]:
ar1=np.array([1,2,3,4],np.float64)

In [46]:
ar1

array([1., 2., 3., 4.])

In [47]:
ar2=np.zeros(3)

In [48]:
ar2


array([0., 0., 0.])

In [49]:
ar2=np.zeros((3,3))

In [50]:
ar2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
ar2=np.ones((3,3))

In [52]:
ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
ar2=np.ones((3,3),np.int32)

In [54]:
ar2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
ar3=np.arange(7)

In [56]:
ar3


array([0, 1, 2, 3, 4, 5, 6])

In [57]:
ar4=np.linspace(1,7,7)                                 #Gives 7 elements at equal distance

In [58]:
ar4


array([1., 2., 3., 4., 5., 6., 7.])

In [59]:
ar4=np.linspace(1,50,26)

In [60]:
ar4

array([ 1.  ,  2.96,  4.92,  6.88,  8.84, 10.8 , 12.76, 14.72, 16.68,
       18.64, 20.6 , 22.56, 24.52, 26.48, 28.44, 30.4 , 32.36, 34.32,
       36.28, 38.24, 40.2 , 42.16, 44.12, 46.08, 48.04, 50.  ])

In [61]:
ar5=np.empty(5)                       #prints random values(just generates an array of given shape)

In [62]:
ar5

array([2.12199579e-314, 6.01346930e-154, 3.55727265e-321, 3.79442416e-321,
       6.01347002e-154])

In [63]:
ar6=np.empty((3,2))

In [64]:
ar6

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [65]:
for i in range(3):
    for j in range(2):
        ar6[i,j]=j

In [66]:
ar6

array([[0., 1.],
       [0., 1.],
       [0., 1.]])

In [67]:
ar7=np.empty_like(my_array2d)               #prints random values of size of my_array2d

In [68]:
ar7

array([[         0,          0,          0],
       [1072693248,          0,          0],
       [         0, 1072693248,          0],
       [         0,          0, 1072693248]])

In [69]:
ar=np.full((4,5),55)

In [70]:
ar


array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [71]:
ar8=np.identity(4)                            #gives identity matrix of shape 5X5

In [72]:
ar8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
ar9=np.eye((5))

In [74]:
ar9


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
ar9=np.eye(5,k=2)                      #Diagonal position changed to index 2 

In [76]:
ar9

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
naveen=np.empty_like(my_array1d)

In [78]:
naveen

array([         1,          1,          0, 1869771365,        900,
                0,   16777984])

In [79]:
naveen[0]=25

In [80]:
naveen.reshape(7,1)             ##Doesn't change the original array

array([[        25],
       [         1],
       [         0],
       [1869771365],
       [       900],
       [         0],
       [  16777984]])

In [81]:
naveen

array([        25,          1,          0, 1869771365,        900,
                0,   16777984])

In [82]:
yadav=np.empty_like(ar8)

In [83]:
yadav.resize(8,2)                            #Changes the original array

In [84]:
yadav

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [85]:
yadav.ravel()                                #converts in 1d array

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

**Matrix Operations can be performed in numpy**

In [86]:
arr1=np.array([[1,2,3,4]
              ,[4,5,5,6]
              ,[7,8,9,6]])

In [87]:
arr2=np.array([[1,2,3,4]
              ,[4,5,5,9]
              ,[1,2,2,3]])

In [88]:
arr1+arr2

array([[ 2,  4,  6,  8],
       [ 8, 10, 10, 15],
       [ 8, 10, 11,  9]])

In [89]:
arr1*arr2

array([[ 1,  4,  9, 16],
       [16, 25, 25, 54],
       [ 7, 16, 18, 18]])

 ***AXIS***

In [90]:
#axis0 is for rows

In [91]:
#axis1 is for columns

In [92]:
#naxis==ndim

In [93]:
arr1.sum(axis=0)   

array([12, 15, 17, 16])

In [94]:
arr2.sum(axis=1)

array([10, 23,  8])

In [95]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 5, 6],
       [7, 8, 9, 6]])

In [96]:
arr1.T                                       #Rows <--> Columns

array([[1, 4, 7],
       [2, 5, 8],
       [3, 5, 9],
       [4, 6, 6]])

In [97]:
flat=arr1.flat                             #makes 1-D iterator over the array.
for i in flat:
    print(i)

1
2
3
4
4
5
5
6
7
8
9
6


In [98]:
arr1.ndim


2

In [99]:
my_array1d.ndim

1

In [100]:
arr1.nbytes

48

In [101]:
arr2.nbytes

48

In [102]:
my_array1d.nbytes

28

In [103]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 5, 6],
       [7, 8, 9, 6]])

In [104]:
arr1.argmax(axis=0)                   #gives array of index of maximum elements of axis 0

array([2, 2, 2, 1], dtype=int64)

In [105]:
arr1.argmax(axis=1)

array([3, 3, 2], dtype=int64)

In [106]:
arr1.argmin(axis=0)

array([0, 0, 0, 0], dtype=int64)

In [107]:
arr2

array([[1, 2, 3, 4],
       [4, 5, 5, 9],
       [1, 2, 2, 3]])

In [108]:
arr2.argsort(axis=0)                         #Sorts indexes in ascending order of values

array([[0, 0, 2, 2],
       [2, 2, 0, 0],
       [1, 1, 1, 1]], dtype=int64)

In [109]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 5, 6],
       [7, 8, 9, 6]])

In [110]:
arr1.argsort(axis=1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [3, 0, 1, 2]], dtype=int64)

In [111]:
my_array1d

array([1, 2, 3, 4, 5, 6, 7])

In [112]:
my_array1d.argsort()                     #is a func

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [113]:
my_array1d.max()                         #is a func

7

In [114]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 5, 6],
       [7, 8, 9, 6]])

In [115]:
np.nonzero(arr1)                   #indices of non zero elements

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [116]:
np.count_nonzero(arr1)

12

In [117]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 2.44948974]])

In [118]:
np.where(arr1>6)                         #gives index

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))